### ISSUE TITLE
Error creating BOM

### ISSUE THREAD

**Issue by hoeken** [APEbbers/BillOfMaterials-WB#127]
Cool new plugin, looks awesome!  I ran into a small problem though:

12:20:00  Running the Python command 'CreateBOM_Overall' failed:
Traceback (most recent call last):
  File "/Users/hoeken/Library/Application Support/FreeCAD/Mod/BillOfMaterials/./BoM_Commands.py", line 303, in Activated
    Gui.Control.showDialog(Load_BoM_Panel.LoadWidget())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hoeken/Library/Application Support/FreeCAD/Mod/BillOfMaterials/./Load_BoM_Panel.py", line 84, in __init__
    self.ReproAdress = Standard_Functions.getReproAdress(os.path.dirname(__file__))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hoeken/Library/Application Support/FreeCAD/Mod/BillOfMaterials/./Standard_Functions_BOM_WB.py", line 422, in getReproAdress
    with (git_dir / "FETCH_HEAD").open("r") as head:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[Errno 2] No such file or directory: '/Users/hoeken/Library/Application Support/FreeCAD/Mod/BillOfMaterials/.git/FETCH_HEAD'

**Comment by APEbbers** [comment]
Had my laptop open so I could create a fix quickly. Can you give it a try? You can update the addon to version 1.0.1 via the add-on manager.

**Comment by hoeken** [comment]
Yep, I just tried it an its working great.  Thanks for the quick fix.
