### ISSUE TITLE
No module named 'PySide6'

### ISSUE THREAD

**Issue by Zolko-123** [APEbbers/BillOfMaterials-WB#13]
after fixing the PATH_TB , the workbench loads fine, but can't execute any function because : 

```
Running the Python command 'CreateBOM_Overall' failed:
Traceback (most recent call last):
File "/home/hubertz/.local/share/FreeCAD/Mod/BillOfMaterials/./BoM_Commands.py", line 295, in Activated
import Load_BoM_Panel
File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "/home/hubertz/.local/share/FreeCAD/Mod/BillOfMaterials/./Load_BoM_Panel.py", line 31, in <module>
import BoM_ManageColumns
File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "/home/hubertz/.local/share/FreeCAD/Mod/BillOfMaterials/./BoM_ManageColumns.py", line 36, in <module>
import Resources.UI.Add_RemoveColumns_ui as Add_RemoveColumns_ui
File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
File "/home/hubertz/.local/share/FreeCAD/Mod/BillOfMaterials/./Resources/UI/Add_RemoveColumns_ui.py", line 11, in <module>
from PySide6.QtCore import (
File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)

No module named 'PySide6'
```

and I see that _PySide6_ is called in quite many places so I can't easily fix them

**Comment by APEbbers** [comment]
I've changed PySide6 to PySide2.
