### ISSUE TITLE
Can only run "Create overall BOM" and "Add or remove columns" commands

### ISSUE THREAD

**Issue by furgo16** [APEbbers/BillOfMaterials-WB#24]
I can only run the "Create overall BOM" and "Add or remove columns" commands successfully. All others fail with a similar error:

```
Running the Python command 'CreateBOM_Raw' failed:
Traceback (most recent call last):
  File "/$HOME/snap/freecad/common/Mod/BillOfMaterials/./BoM_Commands.py", line 247, in Activated
    from General_BOM_Functions import CheckAssemblyType

cannot import name 'CheckAssemblyType' from 'General_BOM_Functions' ($HOME/snap/freecad/common/Mod/BillOfMaterials/./General_BOM_Functions.py)
```

```
Running the Python command 'CreateBOM_1stLevel' failed:
Traceback (most recent call last):
  File "$HOME/snap/freecad/common/Mod/BillOfMaterials/./BoM_Commands.py", line 198, in Activated
    from General_BOM_Functions import CheckAssemblyType

cannot import name 'CheckAssemblyType' from 'General_BOM_Functions' ($HOME/snap/freecad/common/Mod/BillOfMaterials/./General_BOM_Functions.py)
```

My system details:

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36017 (Git) Snap 931
Build type: Release
Branch: main
Hash: 5763ac32b0dd8ac574b791f857eeec0d9d17a4f0
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * BIM 2021.12.0
  * Curves 0.6.23
  * ExplodedAssembly
  * BillOfMaterials 0.0.5.1
  * Ondsel-Lens 2024.1.22.01
  * Assembly4 0.50.7
```

**Comment by didiergm** [comment]
I installed this workbench this morning, using freecad 0.21.2 and the addon manager and I have the same issue. May be it does not download/install the latest source code ?

**Comment by APEbbers** [comment]
Can you see which version is installed from the Add-On manager? Your issue might be related to the other issue that you raised.
I tested from my side and its works. both with FreeCAD 0.21.2 and FreeCAD 0.22dev.
