### ISSUE TITLE
Cannot generate BOM

### ISSUE THREAD

**Issue by tdarlic** [APEbbers/BillOfMaterials-WB#64]
I tried to generate BOM but whatever I try I get the same output
I am on Linux Mint Cinnamon 21.3
When I try to change CreatedBy = os.getlogin() to any fixed string I get the same error?
```
12:13:49  Traceback (most recent call last):
12:13:49    File "/home/tdarlic/.var/app/org.freecadweb.FreeCAD/data/FreeCAD/Mod/BillOfMaterials/./Load_BoM_Panel.py", line 269, in on_CreateBOM_clicked
12:13:49      GetBOM_AppPart.BomFunctions.Start(
12:13:49    File "/home/tdarlic/.var/app/org.freecadweb.FreeCAD/data/FreeCAD/Mod/BillOfMaterials/./GetBOM_AppPart.py", line 646, in Start
12:13:49      raise e
12:13:49    File "/home/tdarlic/.var/app/org.freecadweb.FreeCAD/data/FreeCAD/Mod/BillOfMaterials/./GetBOM_AppPart.py", line 628, in Start
12:13:49      self.CreateTotalBoM(
12:13:49    File "/home/tdarlic/.var/app/org.freecadweb.FreeCAD/data/FreeCAD/Mod/BillOfMaterials/./GetBOM_AppPart.py", line 406, in CreateTotalBoM
12:13:49      General_BOM.createBoMSpreadsheet(TemporaryList)
12:13:49    File "/home/tdarlic/.var/app/org.freecadweb.FreeCAD/data/FreeCAD/Mod/BillOfMaterials/./General_BOM_Functions.py", line 309, in createBoMSpreadsheet
12:13:49      CreatedBy = os.getlogin()
12:13:49                  ^^^^^^^^^^^^^
12:13:49  OSError: [Errno 25] Inappropriate ioctl for device
```

**Comment by APEbbers** [comment]
I've updated the WB to version 0.0.7.1. Can you check if the issue is fixed? I've used a different way to get the username.

**Comment by tdarlic** [comment]
> I've updated the WB to version 0.0.7.1. Can you check if the issue is fixed? I've used a different way to get the username.

It appears to be fixed now.
